### PR TITLE
Renaming 'stylesheets' folder to 'styles'

### PR DESCRIPTION
**Pull request by daverogers**
Per issue #2

### CODE REVIEW

**Comment by daverogers** [comment]
Also adding some theming for the Terminal Status package.

screen shot 2015-05-14 at 6 19 01 pm

**Comment by itsthatguy** [comment]
Cool, is there a reason to not use the color variables defined in https://github.com/itsthatguy/atom-itg-flat/blob/master/stylesheets/colors.less ?

**Comment by daverogers** [comment]
Other than I am a retard? No. :) Though apparently the color I sampled is very different than what is in the color file, which is what it is I guess, I should've at least added it there.

**Comment by daverogers** [comment]
Updated the pull request. Oddly enough, the first commit had duplicated the original itg.dark.flat.less contents, or at least somehow appended my commit to the original file...so probably a good thing that you had me go back through and un-dumbass the doc.

**Comment by itsthatguy** [comment]
nice work! :+1: thanks!

**Pull request merged**
